language: php
sudo: false

php:
  - 7.1
  - 7.2

matrix:
  # Don't wait for the allowed failures to build.
  fast_finish: true

# Cache Composer directorye.
cache:
  directories:
    - $HOME/.composer/cache

script:
 - composer install
 - ./vendor/bin/phpcs --report=checkstyle
 - phpunit --coverage-text

